openapi: 3.0.1
info:
  title: TestAPI
  version: "1.0"
servers:
- url: /endpoint
tags:
- name: TestEndpointProvider-Home
  externalDocs:
    description: TestEndpoint contract, Information Holder Resource role
    url: https://microservice-api-patterns.org/patterns/responsibility/endpointRoles/InformationHolderResource.html
    x-internal-endpoint-slas:
    - type: NONE
      slos:
      - name: TestSLO1
        qualityGoal: A SLO for Test purposes
        measurement:
          value: 1
          unit: hours
paths:
  /Home:
    summary: general data-oriented endpoint
    get:
      tags:
      - TestEndpointProvider-Home
      summary: doSomethingJust4Test
      description: ""
      operationId: Home-doSomethingJust4Test
      parameters:
      - name: attr1
        in: cookie
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      - name: attr2
        in: query
        description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
          target="_blank">Data Element</a>
        required: true
        schema:
          type: string
          description: <a href="https://microservice-api-patterns.org/patterns/structure/elementStereotypes/DataElement"
            target="_blank">Data Element</a>
      responses:
        "200":
          description: doSomethingJust4Test successful execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
components:
  schemas:
    Test:
      type: object
